### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by SasiKiranK** [ayushghd/iSPY#1]
Hi 

Please provide the instructions for installation and config.
What features are available. Call recording, Key logger?

**Comment by ayushghd** [comment]
Hi there!
For installing the app in your mobile, you should have its apk file, that either you can generate through android studio or we will soon upload that file for you. 

Config - Android 6.0+ for perfect user experience.

Features - You can
1. Track multiple users at the same time.
2. Find shortest distance between yourself and other user.
3. Allow/Deny yourself to be tracked.
4. Share your real-time location through WhatsApp, mail etc.
5. Save notes if you want.
6. Call emergency numbers directly through app.
7. Find places near you and near your friend too.
